cloud.microservice.namespace=${CLOUD_NAMESPACE:unknown}
cloud.microservice.name=${MICROSERVICE_NAME:core-operator}
quarkus.operator-sdk.crd.apply=false
quarkus.operator-sdk.crd.generate=false
quarkus.operator-sdk.crd.validate=false
quarkus.operator-sdk.disable-rbac-generation=true
quarkus.operator-sdk.concurrent-reconciliation-threads=${CORE_OPERATOR_CONCURRENCY:16}

quarkus.micrometer.export.prometheus.path=/prometheus
quarkus.micrometer.export.prometheus.enabled=true
metrics.micrometer.enabled=true

quarkus.log.level=${LOG_LEVEL:INFO}
quarkus.log.console.level=${LOG_LEVEL:INFO}
quarkus.log.console.format=[%d{yyyy-MM-dd'T'HH:mm:ss.SSS}] [%-5p] [request_id=%X{requestId}] [tenant_id=%X{tenantId}] [thread=%t] [class=%c{1}] [deployment_session_id=%X{sessionId}] [phase=%X{phase}] [name=%X{resource-name}] [kind=%X{kind}] [subKind=%X{sub-kind}] [channel_request_id=%X{x_channel_request_id}] %s%e%n
quarkus.http.limits.max-header-size=${http.buffer.header.max.size:10240}

apigateway.control-plane.url=${CONTROL_PLANE_INTERNAL_ADDRESS:http://control-plane:8080}
api.dbaas.address=${API_DBAAS_ADDRESS:http://dbaas-aggregator.dbaas:8080}
maas.internal.address=${MAAS_INTERNAL_ADDRESS:http://maas-service.maas:8080}
api.dbaas.agent.address=${API_DBAAS_AGENT_ADDRESS:http://dbaas-agent:8080}
maas.agent.address=${MAAS_AGENT_ADDRESS:http://maas-agent:8080}

quarkus.tls.trust-all=true
quarkus.smallrye-health.root-path=/probes
%dev.DEPLOYMENT_SESSION_ID=1

quarkus.consul-source-config.agent.url=${CONSUL_URL:http://localhost:8500/}
quarkus.consul-source-config.agent.enabled=${CONSUL_ENABLED:false}

cloud.http-client.connect-timeout=${HTTP_CLIENT_CONNECT_TIMEOUT:5s}
cloud.http-client.read-timeout=${HTTP_CLIENT_READ_TIMEOUT:30s}

cloud.composite.structure.xaas.receivers=${COMPOSITE_STRUCTURE_XAAS_RECEIVERS:dbaas,maas}
# XaaSes that can receive composite structure updates. To add one, declare its address here and enlist its name in
# the receivers property above. The name is used as-is in CR conditions, so keep its casing.
cloud.composite.structure.xaas.address.MaaS=${maas.internal.address}
cloud.composite.structure.xaas.address.DBaaS=${api.dbaas.address}
cloud.composite.structure.xaas.read-timeout=5000
cloud.composite.structure.xaas.connect-timeout=1000
cloud.composite.structure.consul.update-timeout=5000

cloud.composite.structure.sync.enabled=true
cloud.composite.structure.sync.check-interval=300000
cloud.consul-long-poll.retry-time=20000
cloud.consul-long-poll.on-success-delay-time=3000

# we should specify it directly, cause it 'true' by default in libs
quarkus.consul-source-config.m2m.enabled=false
