---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: core-operator-role
  labels:
    deployer.cleanup/allow: "true"
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
rules:
- apiGroups:
  - core.netcracker.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - 'configmaps'
  resourceNames:
  - 'composite-structure'
  verbs:
  - get
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - 'configmaps'
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: core-operator-role-events
  labels:
    deployer.cleanup/allow: "true"
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
rules:
- apiGroups:
  - ''
  resources:
  - 'events'
  - 'pods'
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups:
  - 'batch'
  resources:
  - 'jobs'
  verbs:
  - get
  - list
- apiGroups:
  - 'apps'
  resources:
  - 'deployments'
  - 'daemonsets'
  - 'replicasets'
  - 'statefulsets'
  verbs:
  - get
  - list
