name: Build on Commit

on:
  - push

jobs:
  mvn:
    runs-on: ubuntu-latest
    steps:

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven
          restore-keys: |
            maven
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package