name: Build

run-name: >
  Build Java Service — 
  ${{ github.event_name }} (${{ github.head_ref || github.ref_name }}) — 
  [${{ github.event_name == 'push' && format('{0}', github.event.head_commit.message) || '' }}
  ${{ github.event_name == 'pull_request' && format('{0}', github.event.pull_request.title) || '' }}]

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-java-service:
    name: Build java service
    uses: Netcracker/qubership-core-infra/.github/workflows/generic-build-maven-service.yaml@v1.1.0
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
